---
- name: Hello World Sample
  hosts: all
  become: true
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World! This my Git "
        
    - name: install httpd
      yum:
        name: httpd
        state: latest
